name: NPM Releaser
on:
#  push:
#    branches:
#      - main

jobs:
  Release:
    name: Release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Releaser
        uses: ./.github/actions/release-please
        with:
          npm-token: ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
