name: Example workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-20.04

    steps:
      - name: Check the repository
        uses: actions/checkout@v2

      - name: Validate
        uses: ./.github/actions/validate
        with:
          node-version: 16.x
          uses-libindy: true

  tests:
    name: Tests
    needs: validate
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Check the repository
        uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/test
        with:
          node-version: ${{ matrix.node-version }}
